replicaCount: 1

image:
  repository: ghcr.io/pd120424d/version-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-auth


service:
  type: ClusterIP
  port: 8090

resources: {}

ingress:
  enabled: true
  className: traefik
  host: mountain-service.duckdns.org
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  paths:
    - path: /api/v1/health
      pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

