apiVersion: v1
kind: Service
metadata:
  name: {{ include "activity-readmodel-updater.fullname" . }}
  labels:
    {{- include "activity-readmodel-updater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: activity-readmodel-updater
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

