replicaCount: 1

image:
  repository: ghcr.io/pd120424d/docs-aggregator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  EXTERNAL_SCHEME: https
  EXTERNAL_HOST: mountain-service.duckdns.org
  EXTERNAL_BASE_PATH: /api/v1

