replicaCount: 1

image:
  repository: ghcr.io/pd120424d/docs-aggregator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  enabled: false
  className: traefik
  host: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  paths:
    - path: /api/v1/docs
      pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

env:
  EXTERNAL_SCHEME: https
  EXTERNAL_HOST: mountain-service.duckdns.org
  EXTERNAL_BASE_PATH: /api/v1

