replicaCount: 1

image:
  repository: ghcr.io/pd120424d/docs-aggregator
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-auth


service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  enabled: true
  className: traefik
  host: mountain-service.duckdns.org
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: mountain-service-redirect-https@kubernetescrd
  tls:
    secretName: mountain-service-tls
  paths:
    - path: /api/v1/docs
      pathType: Prefix
    - path: /docs/swagger-config.json
      pathType: Exact
    - path: /docs/specs
      pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

env:
  # TODO: Keep http until TLS is enabled on ingress (websecure). Swagger Try-It-Out
  # uses this scheme to call the APIs via the public host. If this is set to https
  # while ingress only serves http, browsers will fail the requests and surface it
  # as a CORS/network error. Switch to https once TLS is configured.
  EXTERNAL_SCHEME: https
  EXTERNAL_HOST: mountain-service.duckdns.org
  EXTERNAL_BASE_PATH: /api/v1
  SERVICES_JSON: |
    [
      {"name":"employee","baseURL":"http://employee-service:8082","healthPath":"/api/v1/health","specPath":"/swagger.json"},
      {"name":"urgency","baseURL":"http://urgency-service:8083","healthPath":"/api/v1/health","specPath":"/swagger.json"},
      {"name":"activity","baseURL":"http://activity-service:8084","healthPath":"/api/v1/health","specPath":"/swagger.json"}
    ]

