# Frontend-only Docker Compose Configuration
# Uses pre-built frontend image from GHCR - no backend dependencies
# Usage: docker-compose -f docker-compose.frontend.yml up

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    network_mode: host
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    volumes:
      - /var/log:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Note: Using host network mode, so no custom networks needed
