# Frontend-only Docker Compose Configuration
# Uses pre-built frontend image from GHCR - no backend dependencies
# Usage: docker-compose -f docker-compose.frontend.yml up

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "${FRONTEND_HTTP_PORT:-80}:80"
      - "${FRONTEND_HTTPS_PORT:-443}:443"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - web
    volumes:
      - /var/log:/var/log
      - ${SSL_CERT_PATH:-./ssl}:/etc/nginx/ssl:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  web:
