version: "3.8"

services:
  employee-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: etf
      POSTGRES_DB: employee_service
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - employee_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-service:
    build:
      context: ./api
      dockerfile: employee/Dockerfile
    environment:
      - DB_HOST=employee-db
      - DB_PORT=5432
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=employee_service
      - APP_ENV=staging
      - JWT_SECRET=my_secret_key
    depends_on:
      employee-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - employee_network
    secrets:
      - db_user
      - db_password

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "9082:9082"
    environment:
      API_URL: "http://employee-service:8082/swagger.json"
    networks:
      - employee_network

networks:
  employee_network:

volumes:
  db_data:

secrets:
  db_user:
    file: ./api/employee/secrets/db_user.txt
  db_password:
    file: ./api/employee/secrets/db_password.txt
