version: "3.8"

services:
  employee-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: etf
      POSTGRES_DB: employee_service
    volumes:
      - db_data_staging:/var/lib/postgresql/data
    ports:
      - "10001:5432"
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-service:
    build:
      context: ./api
      dockerfile: employee/Dockerfile
    environment:
      - DB_HOST=employee-db
      - DB_PORT=5432
      - DB_USER_FILE=/run/secrets/db_user
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=employee_service
      - APP_ENV=staging
      - JWT_SECRET=super-secret-staging-key
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123!@#}
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    depends_on:
      employee-db:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - web
    secrets:
      - db_user
      - db_password
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "9082:9082"
    environment:
      API_URL: "http://employee-service:8082/swagger.json"
    networks:
      - web

  version-service:
    build:
      context: ./api
      dockerfile: version-service/Dockerfile
    image: version-service:latest
    ports:
      - "8090:8090"
    volumes:
      - /var/log:/var/log
    networks:
      - web
    restart: unless-stopped

  frontend:
    build:
      context: ./ui
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=staging
    depends_on:
      - employee-service
    networks:
      - web
    restart: unless-stopped

networks:
  web:

volumes:
  db_data_staging:

secrets:
  db_user:
    file: ./api/employee/secrets/db_user.txt
  db_password:
    file: ./api/employee/secrets/db_password.txt
