name: Test AWS Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Test AWS Secrets
      run: |
        echo "Testing AWS secrets configuration..."
        
        # Check if AWS secrets exist (without revealing values)
        if [ -n "${{ secrets.AWS_DEPLOYMENT_TARGET }}" ]; then
          echo "✅ AWS_DEPLOYMENT_TARGET: Set"
        else
          echo "❌ AWS_DEPLOYMENT_TARGET: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_INSTANCE_IP }}" ]; then
          echo "✅ AWS_INSTANCE_IP: Set"
        else
          echo "❌ AWS_INSTANCE_IP: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_INSTANCE_USER }}" ]; then
          echo "✅ AWS_INSTANCE_USER: Set"
        else
          echo "❌ AWS_INSTANCE_USER: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_SSH_PRIVATE_KEY }}" ]; then
          echo "✅ AWS_SSH_PRIVATE_KEY: Set"
        else
          echo "❌ AWS_SSH_PRIVATE_KEY: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_JWT_SECRET }}" ]; then
          echo "✅ AWS_JWT_SECRET: Set"
        else
          echo "❌ AWS_JWT_SECRET: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_ADMIN_PASSWORD }}" ]; then
          echo "✅ AWS_ADMIN_PASSWORD: Set"
        else
          echo "❌ AWS_ADMIN_PASSWORD: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_SERVICE_AUTH_SECRET }}" ]; then
          echo "✅ AWS_SERVICE_AUTH_SECRET: Set"
        else
          echo "❌ AWS_SERVICE_AUTH_SECRET: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_CORS_ALLOWED_ORIGINS }}" ]; then
          echo "✅ AWS_CORS_ALLOWED_ORIGINS: Set"
        else
          echo "❌ AWS_CORS_ALLOWED_ORIGINS: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_COMPOSE_ENV }}" ]; then
          echo "✅ AWS_COMPOSE_ENV: Set"
        else
          echo "❌ AWS_COMPOSE_ENV: Missing"
        fi
        
        if [ -n "${{ secrets.AWS_SWAGGER_API_URL }}" ]; then
          echo "✅ AWS_SWAGGER_API_URL: Set"
        else
          echo "❌ AWS_SWAGGER_API_URL: Missing"
        fi
        
        echo ""
        echo "Existing Azure secrets:"
        
        if [ -n "${{ secrets.AZURE_VM_HOST }}" ]; then
          echo "✅ AZURE_VM_HOST: Set"
        else
          echo "❌ AZURE_VM_HOST: Missing"
        fi
        
        if [ -n "${{ secrets.AZURE_VM_USER }}" ]; then
          echo "✅ AZURE_VM_USER: Set"
        else
          echo "❌ AZURE_VM_USER: Missing"
        fi
        
        if [ -n "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" ]; then
          echo "✅ AZURE_SSH_PRIVATE_KEY: Set"
        else
          echo "❌ AZURE_SSH_PRIVATE_KEY: Missing"
        fi
        
        if [ -n "${{ secrets.COMPOSE_ENV }}" ]; then
          echo "✅ COMPOSE_ENV: Set"
        else
          echo "❌ COMPOSE_ENV: Missing"
        fi
        
        if [ -n "${{ secrets.SWAGGER_API_URL }}" ]; then
          echo "✅ SWAGGER_API_URL: Set"
        else
          echo "❌ SWAGGER_API_URL: Missing"
        fi
        
        if [ -n "${{ secrets.GHCR_PAT }}" ]; then
          echo "✅ GHCR_PAT: Set"
        else
          echo "❌ GHCR_PAT: Missing"
        fi
