apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mountain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: frontend
          image: ghcr.io/pd120424d/mountain-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mountain-service
spec:
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

