apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mountain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: frontend
          image: ghcr.io/pd120424d/mountain-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: production
            - name: GCP_LOGGING_ENABLED
              value: "true"
            - name: GCP_PROJECT_ID
              value: "reflecting-card-469410-q1"
            - name: LOG_TO_STDOUT_ONLY
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/gcp-logging/key.json"
          volumeMounts:
            - name: gcp-logging-writer-key
              mountPath: /var/secrets/gcp-logging
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      volumes:
        - name: gcp-logging-writer-key
          secret:
            secretName: gcp-logging-writer-key
            items:
              - key: key.json
                path: key.json
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mountain-service
spec:
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

