// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"os"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/urgencies/reset": {
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Брисање свих ургентних ситуација (само за администраторе)",
                "tags": [
                    "urgency"
                ],
                "summary": "Ресетовање свих података",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/urgencies": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Извлачење свих ургентних ситуација",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Извлачење листе ургентних ситуација",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/v1.UrgencyResponse"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Креирање нове ургентне ситуације са свим потребним подацима",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Креирање нове ургентне ситуације",
                "parameters": [
                    {
                        "description": "Urgency data",
                        "name": "urgency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UrgencyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.UrgencyResponse"
                        }
                    }
                }
            }
        },
        "/urgencies/{id}": {
            "get": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Извлачење ургентне ситуације по њеном ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Извлачење ургентне ситуације по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Urgency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UrgencyResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Ажурирање постојеће ургентне ситуације",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Ажурирање ургентне ситуације",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Urgency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated urgency data",
                        "name": "urgency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UrgencyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UrgencyResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Брисање ургентне ситуације по ID",
                "tags": [
                    "urgency"
                ],
                "summary": "Брисање ургентне ситуације",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Urgency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/urgencies/{id}/assign": {
            "post": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Assign urgency to an employee",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Urgency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Assignment payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AssignmentCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "OAuth2Password": []
                    }
                ],
                "tags": [
                    "urgency"
                ],
                "summary": "Unassign urgency",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Urgency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.AssignmentCreateRequest": {
            "type": "object",
            "required": [
                "employeeId"
            ],
            "properties": {
                "employeeId": {
                    "type": "integer"
                }
            }
        },
        "v1.UrgencyCreateRequest": {
            "type": "object",
            "required": [
                "contactPhone",
                "description",
                "firstName",
                "lastName",
                "location"
            ],
            "properties": {
                "contactPhone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/v1.UrgencyLevel"
                },
                "location": {
                    "type": "string"
                }
            }
        },
        "v1.UrgencyLevel": {
            "type": "string",
            "enum": [
                "low",
                "medium",
                "high",
                "critical"
            ],
            "x-enum-varnames": [
                "Low",
                "Medium",
                "High",
                "Critical"
            ]
        },
        "v1.UrgencyResponse": {
            "type": "object",
            "properties": {
                "assignedAt": {
                    "type": "string"
                },
                "assignedEmployeeId": {
                    "type": "integer"
                },
                "contactPhone": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/v1.UrgencyLevel"
                },
                "location": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/v1.UrgencyStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "v1.UrgencyStatus": {
            "type": "string",
            "enum": [
                "open",
                "in_progress",
                "resolved",
                "closed"
            ],
            "x-enum-varnames": [
                "Open",
                "InProgress",
                "Resolved",
                "Closed"
            ]
        },
        "v1.UrgencyUpdateRequest": {
            "type": "object",
            "properties": {
                "contactPhone": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "level": {
                    "$ref": "#/definitions/v1.UrgencyLevel"
                },
                "location": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/v1.UrgencyStatus"
                }
            }
        }
    },
    "securityDefinitions": {
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "/api/v1/oauth/token",
            "scopes": {
                "read": "Grants read access",
                "write": "Grants write access"
            }
        }
    },
    "security": [
        {
            "OAuth2Password": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Сервис за Ургентне ситуације",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	// Override host from environment variable if set
	if host := os.Getenv("SWAGGER_HOST"); host != "" {
		SwaggerInfo.Host = host
	}
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
