basePath: /api/v1
definitions: {}
info:
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Сервис за Хитности
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
