basePath: /api/v1
definitions:
  v1.AssignmentCreateRequest:
    properties:
      employeeId:
        type: integer
    required:
    - employeeId
    type: object
  v1.UrgencyCreateRequest:
    properties:
      contactPhone:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      level:
        $ref: '#/definitions/v1.UrgencyLevel'
      location:
        type: string
    required:
    - contactPhone
    - description
    - firstName
    - lastName
    - location
    type: object
  v1.UrgencyLevel:
    enum:
    - low
    - medium
    - high
    - critical
    type: string
    x-enum-varnames:
    - Low
    - Medium
    - High
    - Critical
  v1.UrgencyResponse:
    properties:
      assignedAt:
        type: string
      assignedEmployeeId:
        type: integer
      contactPhone:
        type: string
      createdAt:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      level:
        $ref: '#/definitions/v1.UrgencyLevel'
      location:
        type: string
      status:
        $ref: '#/definitions/v1.UrgencyStatus'
      updatedAt:
        type: string
    type: object
  v1.UrgencyStatus:
    enum:
    - open
    - in_progress
    - resolved
    - closed
    type: string
    x-enum-varnames:
    - Open
    - InProgress
    - Resolved
    - Closed
  v1.UrgencyUpdateRequest:
    properties:
      contactPhone:
        type: string
      description:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      level:
        $ref: '#/definitions/v1.UrgencyLevel'
      location:
        type: string
      status:
        $ref: '#/definitions/v1.UrgencyStatus'
    type: object
host: localhost:8083
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Сервис за Ургентне ситуације
  version: "1.0"
paths:
  /admin/urgencies/reset:
    delete:
      description: Брисање свих ургентних ситуација (само за администраторе)
      responses:
        "204":
          description: No Content
      security:
      - OAuth2Password: []
      summary: Ресетовање свих података
      tags:
      - urgency
  /urgencies:
    get:
      description: Извлачење свих ургентних ситуација
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/v1.UrgencyResponse'
              type: array
            type: array
      security:
      - OAuth2Password: []
      summary: Извлачење листе ургентних ситуација
      tags:
      - urgency
    post:
      consumes:
      - application/json
      description: Креирање нове ургентне ситуације са свим потребним подацима
      parameters:
      - description: Urgency data
        in: body
        name: urgency
        required: true
        schema:
          $ref: '#/definitions/v1.UrgencyCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.UrgencyResponse'
      security:
      - OAuth2Password: []
      summary: Креирање нове ургентне ситуације
      tags:
      - urgency
  /urgencies/{id}:
    delete:
      description: Брисање ургентне ситуације по ID
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      security:
      - OAuth2Password: []
      summary: Брисање ургентне ситуације
      tags:
      - urgency
    get:
      description: Извлачење ургентне ситуације по њеном ID
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.UrgencyResponse'
      security:
      - OAuth2Password: []
      summary: Извлачење ургентне ситуације по ID
      tags:
      - urgency
    put:
      consumes:
      - application/json
      description: Ажурирање постојеће ургентне ситуације
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated urgency data
        in: body
        name: urgency
        required: true
        schema:
          $ref: '#/definitions/v1.UrgencyUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.UrgencyResponse'
      security:
      - OAuth2Password: []
      summary: Ажурирање ургентне ситуације
      tags:
      - urgency
  /urgencies/{id}/assign:
    delete:
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - OAuth2Password: []
      summary: Unassign urgency
      tags:
      - urgency
    post:
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      - description: Assignment payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.AssignmentCreateRequest'
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - OAuth2Password: []
      summary: Assign urgency to an employee
      tags:
      - urgency
security:
- OAuth2Password: []
securityDefinitions:
  OAuth2Password:
    flow: password
    scopes:
      read: Grants read access
      write: Grants write access
    tokenUrl: /api/v1/oauth/token
    type: oauth2
swagger: "2.0"
