basePath: /api/v1
definitions:
  github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyCreateRequest:
    properties:
      contactPhone:
        type: string
      description:
        type: string
      email:
        type: string
      level:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyLevel'
      location:
        type: string
      name:
        type: string
    required:
    - contactPhone
    - description
    - email
    - location
    - name
    type: object
  github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyLevel:
    enum:
    - low
    - medium
    - high
    - critical
    type: string
    x-enum-varnames:
    - Low
    - Medium
    - High
    - Critical
  github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyResponse:
    properties:
      contactPhone:
        type: string
      createdAt:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: integer
      level:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyLevel'
      location:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyStatus'
      updatedAt:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyStatus:
    enum:
    - open
    - in_progress
    - resolved
    - closed
    type: string
    x-enum-varnames:
    - Open
    - InProgress
    - Resolved
    - Closed
  github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyUpdateRequest:
    properties:
      contactPhone:
        type: string
      description:
        type: string
      email:
        type: string
      level:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyLevel'
      location:
        type: string
      name:
        type: string
      status:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyStatus'
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Сервис за Ургентне ситуације
  version: "1.0"
paths:
  /admin/urgencies/reset:
    delete:
      description: Брисање свих ургентних ситуација (само за администраторе)
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Ресетовање свих података
      tags:
      - urgency
  /urgencies:
    get:
      description: Извлачење свих ургентних ситуација
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyResponse'
              type: array
            type: array
      security:
      - BearerAuth: []
      summary: Извлачење листе ургентних ситуација
      tags:
      - urgency
    post:
      consumes:
      - application/json
      description: Креирање нове ургентне ситуације са свим потребним подацима
      parameters:
      - description: Urgency data
        in: body
        name: urgency
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyResponse'
      security:
      - BearerAuth: []
      summary: Креирање нове ургентне ситуације
      tags:
      - urgency
  /urgencies/{id}:
    delete:
      description: Брисање ургентне ситуације по ID
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
      security:
      - BearerAuth: []
      summary: Брисање ургентне ситуације
      tags:
      - urgency
    get:
      description: Извлачење ургентне ситуације по њеном ID
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyResponse'
      security:
      - BearerAuth: []
      summary: Извлачење ургентне ситуације по ID
      tags:
      - urgency
    put:
      consumes:
      - application/json
      description: Ажурирање постојеће ургентне ситуације
      parameters:
      - description: Urgency ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated urgency data
        in: body
        name: urgency
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_urgency_v1.UrgencyResponse'
      security:
      - BearerAuth: []
      summary: Ажурирање ургентне ситуације
      tags:
      - urgency
security:
- OAuth2Password: []
securityDefinitions:
  OAuth2Password:
    flow: password
    scopes:
      read: Grants read access
      write: Grants write access
    tokenUrl: http://localhost:8082/api/v1/login
    type: oauth2
swagger: "2.0"
