// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/activity_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/activity_service.go -destination=internal/service/activity_service_gomock.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	v1 "github.com/pd120424d/mountain-service/api/contracts/activity/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityService is a mock of ActivityService interface.
type MockActivityService struct {
	ctrl     *gomock.Controller
	recorder *MockActivityServiceMockRecorder
	isgomock struct{}
}

// MockActivityServiceMockRecorder is the mock recorder for MockActivityService.
type MockActivityServiceMockRecorder struct {
	mock *MockActivityService
}

// NewMockActivityService creates a new mock instance.
func NewMockActivityService(ctrl *gomock.Controller) *MockActivityService {
	mock := &MockActivityService{ctrl: ctrl}
	mock.recorder = &MockActivityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityService) EXPECT() *MockActivityServiceMockRecorder {
	return m.recorder
}

// CreateActivity mocks base method.
func (m *MockActivityService) CreateActivity(req *v1.ActivityCreateRequest) (*v1.ActivityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", req)
	ret0, _ := ret[0].(*v1.ActivityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockActivityServiceMockRecorder) CreateActivity(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockActivityService)(nil).CreateActivity), req)
}

// DeleteActivity mocks base method.
func (m *MockActivityService) DeleteActivity(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockActivityServiceMockRecorder) DeleteActivity(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockActivityService)(nil).DeleteActivity), id)
}

// GetActivityByID mocks base method.
func (m *MockActivityService) GetActivityByID(id uint) (*v1.ActivityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityByID", id)
	ret0, _ := ret[0].(*v1.ActivityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityByID indicates an expected call of GetActivityByID.
func (mr *MockActivityServiceMockRecorder) GetActivityByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityByID", reflect.TypeOf((*MockActivityService)(nil).GetActivityByID), id)
}

// GetActivityStats mocks base method.
func (m *MockActivityService) GetActivityStats() (*v1.ActivityStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityStats")
	ret0, _ := ret[0].(*v1.ActivityStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityStats indicates an expected call of GetActivityStats.
func (mr *MockActivityServiceMockRecorder) GetActivityStats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityStats", reflect.TypeOf((*MockActivityService)(nil).GetActivityStats))
}

// ListActivities mocks base method.
func (m *MockActivityService) ListActivities(req *v1.ActivityListRequest) (*v1.ActivityListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivities", req)
	ret0, _ := ret[0].(*v1.ActivityListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActivities indicates an expected call of ListActivities.
func (mr *MockActivityServiceMockRecorder) ListActivities(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivities", reflect.TypeOf((*MockActivityService)(nil).ListActivities), req)
}

// LogActivity mocks base method.
func (m *MockActivityService) LogActivity(description string, employeeID, urgencyID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogActivity", description, employeeID, urgencyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogActivity indicates an expected call of LogActivity.
func (mr *MockActivityServiceMockRecorder) LogActivity(description, employeeID, urgencyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogActivity", reflect.TypeOf((*MockActivityService)(nil).LogActivity), description, employeeID, urgencyID)
}

// ResetAllData mocks base method.
func (m *MockActivityService) ResetAllData() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAllData")
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAllData indicates an expected call of ResetAllData.
func (mr *MockActivityServiceMockRecorder) ResetAllData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAllData", reflect.TypeOf((*MockActivityService)(nil).ResetAllData))
}
