// Code generated by MockGen. DO NOT EDIT.
// Source: firestore_service.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	models "github.com/pd120424d/mountain-service/api/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFirestoreService is a mock of FirestoreService interface.
type MockFirestoreService struct {
	ctrl     *gomock.Controller
	recorder *MockFirestoreServiceMockRecorder
}

// MockFirestoreServiceMockRecorder is the mock recorder for MockFirestoreService.
type MockFirestoreServiceMockRecorder struct {
	mock *MockFirestoreService
}

// NewMockFirestoreService creates a new mock instance.
func NewMockFirestoreService(ctrl *gomock.Controller) *MockFirestoreService {
	mock := &MockFirestoreService{ctrl: ctrl}
	mock.recorder = &MockFirestoreServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirestoreService) EXPECT() *MockFirestoreServiceMockRecorder {
	return m.recorder
}

// CountByUrgencyIDs mocks base method.
func (m *MockFirestoreService) CountByUrgencyIDs(ctx context.Context, ids []uint) (map[uint]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUrgencyIDs", ctx, ids)
	ret0, _ := ret[0].(map[uint]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUrgencyIDs indicates an expected call of CountByUrgencyIDs.
func (mr *MockFirestoreServiceMockRecorder) CountByUrgencyIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUrgencyIDs", reflect.TypeOf((*MockFirestoreService)(nil).CountByUrgencyIDs), ctx, ids)
}

// ListAll mocks base method.
func (m *MockFirestoreService) ListAll(ctx context.Context, limit int) ([]models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx, limit)
	ret0, _ := ret[0].([]models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockFirestoreServiceMockRecorder) ListAll(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockFirestoreService)(nil).ListAll), ctx, limit)
}

// ListAllCursor mocks base method.
func (m *MockFirestoreService) ListAllCursor(ctx context.Context, pageSize int, pageToken string) ([]models.Activity, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCursor", ctx, pageSize, pageToken)
	ret0, _ := ret[0].([]models.Activity)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAllCursor indicates an expected call of ListAllCursor.
func (mr *MockFirestoreServiceMockRecorder) ListAllCursor(ctx, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCursor", reflect.TypeOf((*MockFirestoreService)(nil).ListAllCursor), ctx, pageSize, pageToken)
}

// ListByUrgency mocks base method.
func (m *MockFirestoreService) ListByUrgency(ctx context.Context, urgencyID uint, limit int) ([]models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUrgency", ctx, urgencyID, limit)
	ret0, _ := ret[0].([]models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUrgency indicates an expected call of ListByUrgency.
func (mr *MockFirestoreServiceMockRecorder) ListByUrgency(ctx, urgencyID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUrgency", reflect.TypeOf((*MockFirestoreService)(nil).ListByUrgency), ctx, urgencyID, limit)
}

// ListByUrgencyCursor mocks base method.
func (m *MockFirestoreService) ListByUrgencyCursor(ctx context.Context, urgencyID uint, pageSize int, pageToken string) ([]models.Activity, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUrgencyCursor", ctx, urgencyID, pageSize, pageToken)
	ret0, _ := ret[0].([]models.Activity)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUrgencyCursor indicates an expected call of ListByUrgencyCursor.
func (mr *MockFirestoreServiceMockRecorder) ListByUrgencyCursor(ctx, urgencyID, pageSize, pageToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUrgencyCursor", reflect.TypeOf((*MockFirestoreService)(nil).ListByUrgencyCursor), ctx, urgencyID, pageSize, pageToken)
}
