// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/activity_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repositories/activity_repository.go -destination=internal/repositories/activity_repository_gomock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	context "context"
	reflect "reflect"

	model "github.com/pd120424d/mountain-service/api/activity/internal/model"
	models "github.com/pd120424d/mountain-service/api/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityRepository) Create(ctx context.Context, activity *model.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActivityRepositoryMockRecorder) Create(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityRepository)(nil).Create), ctx, activity)
}

// CreateWithOutbox mocks base method.
func (m *MockActivityRepository) CreateWithOutbox(ctx context.Context, activity *model.Activity, event *models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithOutbox", ctx, activity, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithOutbox indicates an expected call of CreateWithOutbox.
func (mr *MockActivityRepositoryMockRecorder) CreateWithOutbox(ctx, activity, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithOutbox", reflect.TypeOf((*MockActivityRepository)(nil).CreateWithOutbox), ctx, activity, event)
}

// CreateBatchWithOutbox mocks base method.
func (m *MockActivityRepository) CreateBatchWithOutbox(ctx context.Context, activities []*model.Activity, events []*models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithOutbox", ctx, activities, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatchWithOutbox indicates an expected call of CreateBatchWithOutbox.
func (mr *MockActivityRepositoryMockRecorder) CreateBatchWithOutbox(ctx, activities, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithOutbox", reflect.TypeOf((*MockActivityRepository)(nil).CreateBatchWithOutbox), ctx, activities, events)
}

// Delete mocks base method.
func (m *MockActivityRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActivityRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActivityRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockActivityRepository) GetByID(ctx context.Context, id uint) (*model.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActivityRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivityRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockActivityRepository) List(ctx context.Context, filter *model.ActivityFilter) ([]model.Activity, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]model.Activity)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockActivityRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockActivityRepository)(nil).List), ctx, filter)
}

// ResetAllData mocks base method.
func (m *MockActivityRepository) ResetAllData(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetAllData", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetAllData indicates an expected call of ResetAllData.
func (mr *MockActivityRepositoryMockRecorder) ResetAllData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetAllData", reflect.TypeOf((*MockActivityRepository)(nil).ResetAllData), ctx)
}
