replicaCount: 1

image:
  repository: ghcr.io/pd120424d/activity-service
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-auth


service:
  type: ClusterIP
  port: 8084

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

ingress:
  enabled: true
  className: traefik
  host: mountain-service.duckdns.org
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  paths:
    - path: /api/v1/activities
      pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

secrets:
  dbCommon: db-common
  dbService: activity-db
  cloudSQLSA: gcp-sa
  cloudSQLSAKey: key.json
  cloudSQLPrimarySecret: cloudsql-activity
  cloudSQLPrimaryKey: INSTANCE_CONNECTION_NAME

cloudSQL:
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
  # activity does not use replicas
  useAggregatedSecret: false

pgbouncer:
  image: ghcr.io/pd120424d/pgbouncer:1.24.1
  ports:
    primary: 6432
  proxyPorts:
    primary: 55432
  pool:
    pool_mode: transaction
    default_pool_size: 20
    min_pool_size: 5
    reserve_pool_size: 5
    auth_type: plain

appEnv:
  DB_HOST: 127.0.0.1
  DB_PORT: "6432"
  GOMEMLIMIT: "400Mi"

  DB_SSLMODE: disable
  REDIS_ADDR: redis:6379
  GOOGLE_CLOUD_PROJECT: reflecting-card-469410-q1
  FIREBASE_PROJECT_ID: reflecting-card-469410-q1
  OUTBOX_PUBLISH_INTERVAL_SECONDS: "10"
  OUTBOX_PUBLISH_BATCH_SIZE: "100"
pubsub:
  enabled: true
  topic: activity-events

firestore:
  enabled: true

