apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-frontend
  namespace: mountain-service
  labels:
    app: fluent-bit-frontend
spec:
  selector:
    matchLabels:
      app: fluent-bit-frontend
  template:
    metadata:
      labels:
        app: fluent-bit-frontend
    spec:
      serviceAccountName: fluent-bit-sa
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containerlogs
          hostPath:
            path: /var/log/containers
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: gcp-logging-secret
          secret:
            secretName: gcp-logging-writer-key
            items:
              - key: key.json
                path: key.json
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: containerlogs
              mountPath: /var/log/containers
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: gcp-logging-secret
              mountPath: /var/secrets/gcp-logging
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi

