// Code generated by MockGen. DO NOT EDIT.
// Source: shift_repository.go
//
// Generated by this command:
//
//	mockgen -source=shift_repository.go -destination=shift_repository_gomock.go -package=repositories mountain_service/employee/internal/repositories -imports=gomock=go.uber.org/mock/gomock
//
// Package repositories is a generated GoMock package.
package repositories

import (
	model "github.com/pd120424d/mountain-service/api/employee/internal/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockShiftRepository is a mock of ShiftRepository interface.
type MockShiftRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShiftRepositoryMockRecorder
}

// MockShiftRepositoryMockRecorder is the mock recorder for MockShiftRepository.
type MockShiftRepositoryMockRecorder struct {
	mock *MockShiftRepository
}

// NewMockShiftRepository creates a new mock instance.
func NewMockShiftRepository(ctrl *gomock.Controller) *MockShiftRepository {
	mock := &MockShiftRepository{ctrl: ctrl}
	mock.recorder = &MockShiftRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShiftRepository) EXPECT() *MockShiftRepositoryMockRecorder {
	return m.recorder
}

// AssignEmployee mocks base method.
func (m *MockShiftRepository) AssignEmployee(shiftDate time.Time, shiftType int, employeeID uint, employeeRole string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignEmployee", shiftDate, shiftType, employeeID, employeeRole)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignEmployee indicates an expected call of AssignEmployee.
func (mr *MockShiftRepositoryMockRecorder) AssignEmployee(shiftDate, shiftType, employeeID, employeeRole interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignEmployee", reflect.TypeOf((*MockShiftRepository)(nil).AssignEmployee), shiftDate, shiftType, employeeID, employeeRole)
}

// GetShiftAvailability mocks base method.
func (m *MockShiftRepository) GetShiftAvailability(date time.Time) (map[int]map[model.ProfileType]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftAvailability", date)
	ret0, _ := ret[0].(map[int]map[model.ProfileType]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftAvailability indicates an expected call of GetShiftAvailability.
func (mr *MockShiftRepositoryMockRecorder) GetShiftAvailability(date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftAvailability", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftAvailability), date)
}

// GetShiftsByEmployeeID mocks base method.
func (m *MockShiftRepository) GetShiftsByEmployeeID(employeeID uint, result *[]model.Shift) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftsByEmployeeID", employeeID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetShiftsByEmployeeID indicates an expected call of GetShiftsByEmployeeID.
func (mr *MockShiftRepositoryMockRecorder) GetShiftsByEmployeeID(employeeID, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftsByEmployeeID", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftsByEmployeeID), employeeID, result)
}

// RemoveEmployeeFromShift mocks base method.
func (m *MockShiftRepository) RemoveEmployeeFromShift(assignmentID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEmployeeFromShift", assignmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEmployeeFromShift indicates an expected call of RemoveEmployeeFromShift.
func (mr *MockShiftRepositoryMockRecorder) RemoveEmployeeFromShift(assignmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEmployeeFromShift", reflect.TypeOf((*MockShiftRepository)(nil).RemoveEmployeeFromShift), assignmentID)
}
