// Code generated by MockGen. DO NOT EDIT.
// Source: shift_repository.go
//
// Generated by this command:
//
//	mockgen -source=shift_repository.go -destination=shift_repository_gomock.go -package=repositories
//

// Package repositories is a generated GoMock package.
package repositories

import (
	reflect "reflect"
	time "time"

	model "github.com/pd120424d/mountain-service/api/employee/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockShiftRepository is a mock of ShiftRepository interface.
type MockShiftRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShiftRepositoryMockRecorder
	isgomock struct{}
}

// MockShiftRepositoryMockRecorder is the mock recorder for MockShiftRepository.
type MockShiftRepositoryMockRecorder struct {
	mock *MockShiftRepository
}

// NewMockShiftRepository creates a new mock instance.
func NewMockShiftRepository(ctrl *gomock.Controller) *MockShiftRepository {
	mock := &MockShiftRepository{ctrl: ctrl}
	mock.recorder = &MockShiftRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShiftRepository) EXPECT() *MockShiftRepositoryMockRecorder {
	return m.recorder
}

// AssignedToShift mocks base method.
func (m *MockShiftRepository) AssignedToShift(employeeID, shiftID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignedToShift", employeeID, shiftID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignedToShift indicates an expected call of AssignedToShift.
func (mr *MockShiftRepositoryMockRecorder) AssignedToShift(employeeID, shiftID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignedToShift", reflect.TypeOf((*MockShiftRepository)(nil).AssignedToShift), employeeID, shiftID)
}

// CountAssignmentsByProfile mocks base method.
func (m *MockShiftRepository) CountAssignmentsByProfile(shiftID uint, profileType model.ProfileType) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAssignmentsByProfile", shiftID, profileType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAssignmentsByProfile indicates an expected call of CountAssignmentsByProfile.
func (mr *MockShiftRepositoryMockRecorder) CountAssignmentsByProfile(shiftID, profileType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAssignmentsByProfile", reflect.TypeOf((*MockShiftRepository)(nil).CountAssignmentsByProfile), shiftID, profileType)
}

// CreateAssignment mocks base method.
func (m *MockShiftRepository) CreateAssignment(employeeID, shiftID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssignment", employeeID, shiftID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAssignment indicates an expected call of CreateAssignment.
func (mr *MockShiftRepositoryMockRecorder) CreateAssignment(employeeID, shiftID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssignment", reflect.TypeOf((*MockShiftRepository)(nil).CreateAssignment), employeeID, shiftID)
}

// GetOnCallEmployees mocks base method.
func (m *MockShiftRepository) GetOnCallEmployees(currentTime time.Time, shiftBuffer time.Duration) ([]model.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnCallEmployees", currentTime, shiftBuffer)
	ret0, _ := ret[0].([]model.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnCallEmployees indicates an expected call of GetOnCallEmployees.
func (mr *MockShiftRepositoryMockRecorder) GetOnCallEmployees(currentTime, shiftBuffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnCallEmployees", reflect.TypeOf((*MockShiftRepository)(nil).GetOnCallEmployees), currentTime, shiftBuffer)
}

// GetOrCreateShift mocks base method.
func (m *MockShiftRepository) GetOrCreateShift(shiftDate time.Time, shiftType int) (*model.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateShift", shiftDate, shiftType)
	ret0, _ := ret[0].(*model.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateShift indicates an expected call of GetOrCreateShift.
func (mr *MockShiftRepositoryMockRecorder) GetOrCreateShift(shiftDate, shiftType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateShift", reflect.TypeOf((*MockShiftRepository)(nil).GetOrCreateShift), shiftDate, shiftType)
}

// GetShiftAvailability mocks base method.
func (m *MockShiftRepository) GetShiftAvailability(start, end time.Time) (*model.ShiftsAvailabilityRange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftAvailability", start, end)
	ret0, _ := ret[0].(*model.ShiftsAvailabilityRange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftAvailability indicates an expected call of GetShiftAvailability.
func (mr *MockShiftRepositoryMockRecorder) GetShiftAvailability(start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftAvailability", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftAvailability), start, end)
}

// GetShiftAvailabilityWithEmployeeStatus mocks base method.
func (m *MockShiftRepository) GetShiftAvailabilityWithEmployeeStatus(employeeID uint, start, end time.Time) (*model.ShiftsAvailabilityWithEmployeeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftAvailabilityWithEmployeeStatus", employeeID, start, end)
	ret0, _ := ret[0].(*model.ShiftsAvailabilityWithEmployeeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShiftAvailabilityWithEmployeeStatus indicates an expected call of GetShiftAvailabilityWithEmployeeStatus.
func (mr *MockShiftRepositoryMockRecorder) GetShiftAvailabilityWithEmployeeStatus(employeeID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftAvailabilityWithEmployeeStatus", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftAvailabilityWithEmployeeStatus), employeeID, start, end)
}

// GetShiftsByEmployeeID mocks base method.
func (m *MockShiftRepository) GetShiftsByEmployeeID(employeeID uint, result *[]model.Shift) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftsByEmployeeID", employeeID, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetShiftsByEmployeeID indicates an expected call of GetShiftsByEmployeeID.
func (mr *MockShiftRepositoryMockRecorder) GetShiftsByEmployeeID(employeeID, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftsByEmployeeID", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftsByEmployeeID), employeeID, result)
}

// GetShiftsByEmployeeIDInDateRange mocks base method.
func (m *MockShiftRepository) GetShiftsByEmployeeIDInDateRange(employeeID uint, startDate, endDate time.Time, result *[]model.Shift) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShiftsByEmployeeIDInDateRange", employeeID, startDate, endDate, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetShiftsByEmployeeIDInDateRange indicates an expected call of GetShiftsByEmployeeIDInDateRange.
func (mr *MockShiftRepositoryMockRecorder) GetShiftsByEmployeeIDInDateRange(employeeID, startDate, endDate, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShiftsByEmployeeIDInDateRange", reflect.TypeOf((*MockShiftRepository)(nil).GetShiftsByEmployeeIDInDateRange), employeeID, startDate, endDate, result)
}

// RemoveEmployeeFromShiftByDetails mocks base method.
func (m *MockShiftRepository) RemoveEmployeeFromShiftByDetails(employeeID uint, shiftDate time.Time, shiftType int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveEmployeeFromShiftByDetails", employeeID, shiftDate, shiftType)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveEmployeeFromShiftByDetails indicates an expected call of RemoveEmployeeFromShiftByDetails.
func (mr *MockShiftRepositoryMockRecorder) RemoveEmployeeFromShiftByDetails(employeeID, shiftDate, shiftType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveEmployeeFromShiftByDetails", reflect.TypeOf((*MockShiftRepository)(nil).RemoveEmployeeFromShiftByDetails), employeeID, shiftDate, shiftType)
}
