apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginx.configMapName }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}

