apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: mountain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: activity
          image: ghcr.io/pd120424d/activity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            # Database Configuration
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: db-common, key: DB_PORT } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db-common, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: activity-db, key: DB_PASSWORD } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: activity-db, key: DB_NAME } }
            - name: DB_SSLMODE
              value: "disable"
            # Authentication
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: app-shared, key: JWT_SECRET } }
            - name: ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: app-shared, key: ADMIN_PASSWORD } }
            - name: SERVICE_AUTH_SECRET
              valueFrom: { secretKeyRef: { name: app-shared, key: SERVICE_AUTH_SECRET } }
            # CQRS Configuration
            - name: GOOGLE_CLOUD_PROJECT
              value: "reflecting-card-469410-q1"
            - name: FIREBASE_PROJECT_ID
              value: "reflecting-card-469410-q1"
            - name: USE_FIREBASE_READ
              value: "true"
            - name: PUBSUB_TOPIC
              value: "activity-events"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/gcp/key.json"
            - name: GCP_LOGGING_ENABLED
              value: "true"
            - name: GCP_PROJECT_ID
              value: "reflecting-card-469410-q1"
            - name: LOG_TO_STDOUT_ONLY
              value: "true"

            # External Services
            - name: EMPLOYEE_SERVICE_URL
              value: "http://employee-service.mountain-service.svc.cluster.local:8082/api/v1"
            - name: URGENCY_SERVICE_URL
              value: "http://urgency-service.mountain-service.svc.cluster.local:8083/api/v1"
          volumeMounts:
            - name: gcp-activity-api-key
              mountPath: /var/secrets/gcp
              readOnly: true
            - name: gcp-logging-writer-key
              mountPath: /var/secrets/gcp-logging
              readOnly: true

          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
          args:
            - "--port=5432"
            - "--address=127.0.0.1"
            - "--credentials-file=/var/secrets/key.json"
            - "$(INSTANCE_CONNECTION_NAME)"
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-activity
                  key: INSTANCE_CONNECTION_NAME
          volumeMounts:
            - name: gcp-sa
              mountPath: /var/secrets
              readOnly: true
            - name: gcp-activity-api-key
              mountPath: /var/secrets/gcp
              readOnly: true
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
              - key: key.json
                path: key.json
        - name: gcp-activity-api-key
          secret:
            secretName: gcp-activity-api-key
            items:
              - key: key.json
                path: key.json
        - name: gcp-logging-writer-key
          secret:
            secretName: gcp-logging-writer-key
            items:
              - key: key.json
                path: key.json

---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: mountain-service
spec:
  selector:
    app: activity-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

