apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-readmodel-updater
  namespace: mountain-service
spec:
  replicas: 1  # Only one instance to avoid duplicate processing
  selector:
    matchLabels:
      app: activity-readmodel-updater
  template:
    metadata:
      labels:
        app: activity-readmodel-updater
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: activity-readmodel-updater
          image: ghcr.io/pd120424d/activity-readmodel-updater:latest
          ports:
            - containerPort: 8090
          env:
            # Database Configuration (for outbox polling)
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: db-common, key: DB_PORT } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db-common, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: activity-db, key: DB_PASSWORD } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: activity-db, key: DB_NAME } }
            - name: DB_SSLMODE
              value: "disable"
            # CQRS Configuration
            - name: GOOGLE_CLOUD_PROJECT
              value: "reflecting-card-469410-q1"
            - name: FIREBASE_PROJECT_ID
              value: "reflecting-card-469410-q1"
            - name: PUBSUB_TOPIC
              value: "activity-events"
            - name: PUBSUB_SUBSCRIPTION
              value: "activity-events-sub"
            - name: OUTBOX_POLL_INTERVAL_SECONDS
              value: "10"
            - name: HEALTH_PORT
              value: "8090"
            - name: LOG_LEVEL
              value: "info"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/gcp/key.json"
          volumeMounts:
            - name: gcp-activity-updater-key
              mountPath: /var/secrets/gcp
              readOnly: true
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
          args:
            - "--port=5432"
            - "--address=127.0.0.1"
            - "--credentials-file=/var/secrets/key.json"
            - "$(INSTANCE_CONNECTION_NAME)"
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-activity
                  key: INSTANCE_CONNECTION_NAME
          volumeMounts:
            - name: gcp-sa
              mountPath: /var/secrets
              readOnly: true
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
            items:
              - key: key.json
                path: key.json
        - name: gcp-activity-updater-key
          secret:
            secretName: gcp-activity-updater-key
            items:
              - key: key.json
                path: key.json
