apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mountain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        # Optional: Add persistence if needed
        # volumeMounts:
        # - name: redis-data
        #   mountPath: /data
      # volumes:
      # - name: redis-data
      #   persistentVolumeClaim:
      #     claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mountain
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP
