apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-service
  namespace: mountain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-service
  template:
    metadata:
      labels:
        app: version-service
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: version
          image: ghcr.io/pd120424d/version-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: GCP_LOGGING_ENABLED
              value: "true"
            - name: GCP_PROJECT_ID
              value: "reflecting-card-469410-q1"
            - name: LOG_TO_STDOUT_ONLY
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/gcp-logging/key.json"
          volumeMounts:
            - name: gcp-logging-writer-key
              mountPath: /var/secrets/gcp-logging
              readOnly: true
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: gcp-logging-writer-key
          secret:
            secretName: gcp-logging-writer-key
            items:
              - key: key.json
                path: key.json
---
apiVersion: v1
kind: Service
metadata:
  name: version-service
  namespace: mountain-service
spec:
  selector:
    app: version-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP

