apiVersion: v1
kind: ConfigMap
metadata:
  name: urgency-pgbouncer-config
  namespace: mountain-service
  labels:
    app: urgency-service
    component: pgbouncer
    tier: data

data:
  pgbouncer.ini: |
    [databases]
    # Map logical names to the same physical Cloud SQL database via different local proxy ports
    urgency_primary = host=127.0.0.1 port=55432 dbname=urgency_service_db
    urgency_replica1 = host=127.0.0.1 port=56432 dbname=urgency_service_db
    urgency_replica2 = host=127.0.0.1 port=57432 dbname=urgency_service_db

    [pgbouncer]
    listen_addr = 127.0.0.1
    listen_port = 6432
    auth_type = trust
    pool_mode = transaction
    max_client_conn = 1000
    default_pool_size = 20
    min_pool_size = 5
    reserve_pool_size = 5
    # Log to stdout
    syslog = 0
    logfile = /dev/stdout
    pidfile = /tmp/pgbouncer.pid
  users.txt: |
    # Using trust auth; user list not required

