apiVersion: v1
kind: Service
metadata:
  name: {{ include "docs-aggregator.fullname" . }}
  labels:
    {{- include "docs-aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: docs-aggregator
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

