// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/reset": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Брише све запослене, смене и повезане податке из система (само за админе)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "админ"
                ],
                "summary": "Ресетовање свих података",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.MessageResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Преузимање свих запослених",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "запослени"
                ],
                "summary": "Преузимање листе запослених",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/model.EmployeeResponse"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Креирање новог запосленог у систему",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "запослени"
                ],
                "summary": "Креирање новог запосленог",
                "parameters": [
                    {
                        "description": "Подаци о новом запосленом",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ажурирање запосленог по ID-ју",
                "tags": [
                    "запослени"
                ],
                "summary": "Ажурирање запосленог",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запосленог",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Подаци за ажурирање запосленог",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Брисање запосленог по ID-ју",
                "tags": [
                    "запослени"
                ],
                "summary": "Брисање запосленог",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запосленог",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/employees/{id}/shifts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Дохватање смена за запосленог по ID-ју",
                "tags": [
                    "запослени"
                ],
                "summary": "Дохватање смена за запосленог",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запосленог",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.ShiftResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Додељује смену запосленом по ID-ју",
                "tags": [
                    "запослени"
                ],
                "summary": "Додељује смену запосленом",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запосленог",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Подаци о смени",
                        "name": "shift",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AssignShiftRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.AssignShiftResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Уклањање смене за запосленог по ID-ју и подацима о смени",
                "tags": [
                    "запослени"
                ],
                "summary": "Уклањање смене за запосленог",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID запосленог",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Подаци о смени",
                        "name": "shift",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RemoveShiftRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Пријавање запосленог са корисничким именом и лозинком",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "запослени"
                ],
                "summary": "Пријавање запосленог",
                "parameters": [
                    {
                        "description": "Корисничко име и лозинка",
                        "name": "employee",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EmployeeLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/shifts/availability": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Дохватање доступности смена за одређени дан",
                "tags": [
                    "запослени"
                ],
                "summary": "Дохватање доступности смена",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дан за који се проверава доступност смена",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ShiftAvailabilityResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AssignShiftRequest": {
            "type": "object",
            "required": [
                "shiftDate",
                "shiftType"
            ],
            "properties": {
                "shiftDate": {
                    "type": "string"
                },
                "shiftType": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 1
                }
            }
        },
        "model.AssignShiftResponse": {
            "type": "object",
            "required": [
                "id",
                "shiftDate",
                "shiftType"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "shiftDate": {
                    "type": "string"
                },
                "shiftType": {
                    "type": "integer"
                }
            }
        },
        "model.EmployeeCreateRequest": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "gender",
                "lastName",
                "password",
                "phone",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "profileType": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.EmployeeLogin": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.EmployeeResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profilePicture": {
                    "description": "this may be represented as a byte array if we read the picture from somewhere for an example",
                    "type": "string"
                },
                "profileType": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.EmployeeUpdateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "profileType": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Error message"
                }
            }
        },
        "model.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Success message"
                }
            }
        },
        "model.RemoveShiftRequest": {
            "type": "object",
            "required": [
                "shiftDate",
                "shiftType"
            ],
            "properties": {
                "shiftDate": {
                    "type": "string"
                },
                "shiftType": {
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 1
                }
            }
        },
        "model.ShiftAvailabilityDto": {
            "type": "object",
            "properties": {
                "Medic": {
                    "type": "integer"
                },
                "Technical": {
                    "type": "integer"
                }
            }
        },
        "model.ShiftAvailabilityPerDay": {
            "type": "object",
            "properties": {
                "1": {
                    "$ref": "#/definitions/model.ShiftAvailabilityDto"
                },
                "2": {
                    "$ref": "#/definitions/model.ShiftAvailabilityDto"
                },
                "3": {
                    "$ref": "#/definitions/model.ShiftAvailabilityDto"
                }
            }
        },
        "model.ShiftAvailabilityResponse": {
            "type": "object",
            "properties": {
                "days": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/model.ShiftAvailabilityPerDay"
                    }
                }
            }
        },
        "model.ShiftResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "shiftDate": {
                    "type": "string"
                },
                "shiftType": {
                    "description": "1: 6am-2pm, 2: 2pm-10pm, 3: 10pm-6am, \u003c 1 or \u003e 3: invalid",
                    "type": "integer"
                }
            }
        },
        "model.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Сервис за Запослене",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
