basePath: /api/v1
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  model.AssignShiftRequest:
    properties:
      profileType:
        enum:
        - Medic
        - Technical
        type: string
      shiftDate:
        type: string
      shiftType:
        maximum: 3
        minimum: 1
        type: integer
    required:
    - profileType
    - shiftDate
    - shiftType
    type: object
  model.AssignShiftResponse:
    properties:
      id:
        type: integer
      profileType:
        type: string
      shiftDate:
        type: string
      shiftType:
        type: integer
    type: object
  model.EmployeeCreateRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      profilePicture:
        type: string
      profileType:
        type: string
      username:
        type: string
    required:
    - email
    - firstName
    - gender
    - lastName
    - password
    - phone
    - username
    type: object
  model.EmployeeLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.EmployeeResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      id:
        type: integer
      lastName:
        type: string
      phone:
        type: string
      profilePicture:
        description: this may be represented as a byte array if we read the picture
          from somewhere for an example
        type: string
      profileType:
        type: string
      username:
        type: string
    type: object
  model.EmployeeUpdateRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      phone:
        type: string
      profilePicture:
        type: string
      profileType:
        type: string
    type: object
  model.RemoveShiftRequest:
    properties:
      id:
        type: integer
    type: object
  model.ShiftResponse:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      shiftDate:
        type: string
      shiftType:
        description: '1: 6am-2pm, 2: 2pm-10pm, 3: 10pm-6am, < 1 or > 3: invalid'
        type: integer
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Сервис за Запослене
  version: "1.0"
paths:
  /employees:
    get:
      description: Преузимање свих запослених
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/model.EmployeeResponse'
              type: array
            type: array
      security:
      - BearerAuth: []
      summary: Преузимање листе запослених
      tags:
      - запослени
    post:
      consumes:
      - application/json
      description: Креирање новог запосленог у систему
      parameters:
      - description: Подаци о новом запосленом
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/model.EmployeeCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.EmployeeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Креирање новог запосленог
      tags:
      - запослени
  /employees/{id}:
    delete:
      description: Брисање запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - BearerAuth: []
      summary: Брисање запосленог
      tags:
      - запослени
    put:
      description: Ажурирање запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци за ажурирање запосленог
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/model.EmployeeUpdateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.EmployeeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - BearerAuth: []
      summary: Ажурирање запосленог
      tags:
      - запослени
  /employees/{id}/shifts:
    delete:
      description: Уклањање смене за запосленог по ID-ју и подацима о смени
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци о смени
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/model.RemoveShiftRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - BearerAuth: []
      summary: Уклањање смене за запосленог
      tags:
      - запослени
    get:
      description: Дохватање смена за запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ShiftResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Дохватање смена за запосленог
      tags:
      - запослени
    post:
      description: Додељује смену запосленом по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци о смени
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/model.AssignShiftRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.AssignShiftResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - BearerAuth: []
      summary: Додељује смену запосленом
      tags:
      - запослени
  /login:
    post:
      consumes:
      - application/json
      description: Пријавање запосленог са корисничким именом и лозинком
      parameters:
      - description: Корисничко име и лозинка
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/model.EmployeeLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
      summary: Пријавање запосленог
      tags:
      - запослени
  /shifts/availability:
    get:
      description: Дохватање доступности смена за одређени дан
      parameters:
      - description: Дан за који се проверава доступност смена
        in: query
        name: date
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - BearerAuth: []
      summary: Дохватање доступности смена
      tags:
      - запослени
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
