basePath: /api/v1
definitions:
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ActiveEmergenciesResponse:
    properties:
      hasActiveEmergencies:
        type: boolean
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.AssignShiftRequest:
    properties:
      shiftDate:
        type: string
      shiftType:
        maximum: 3
        minimum: 1
        type: integer
    required:
    - shiftDate
    - shiftType
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.AssignShiftResponse:
    properties:
      id:
        type: integer
      shiftDate:
        type: string
      shiftType:
        type: integer
    required:
    - id
    - shiftDate
    - shiftType
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeCreateRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      profilePicture:
        type: string
      profileType:
        type: string
      username:
        type: string
    required:
    - email
    - firstName
    - gender
    - lastName
    - password
    - phone
    - username
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeLogin:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      id:
        type: integer
      lastName:
        type: string
      phone:
        type: string
      profilePicture:
        description: this may be represented as a byte array if we read the picture
          from somewhere for an example
        type: string
      profileType:
        type: string
      username:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeUpdateRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      phone:
        type: string
      profilePicture:
        type: string
      profileType:
        type: string
      username:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.MessageResponse:
    properties:
      message:
        type: string
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.OnCallEmployeesResponse:
    properties:
      employees:
        items:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeResponse'
        type: array
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.RemoveShiftRequest:
    properties:
      shiftDate:
        type: string
      shiftType:
        maximum: 3
        minimum: 1
        type: integer
    required:
    - shiftDate
    - shiftType
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailability:
    properties:
      available:
        type: boolean
      employees:
        items:
          type: string
        type: array
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailabilityPerDay:
    properties:
      shift1:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailability'
      shift2:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailability'
      shift3:
        $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailability'
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailabilityResponse:
    properties:
      days:
        additionalProperties:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailabilityPerDay'
        type: object
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftResponse:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      shiftDate:
        type: string
      shiftType:
        description: '1: 6am-2pm, 2: 2pm-10pm, 3: 10pm-6am, < 1 or > 3: invalid'
        type: integer
    type: object
  github_com_pd120424d_mountain-service_api_contracts_employee_v1.TokenResponse:
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Сервис за Запослене
  version: "1.0"
paths:
  /admin/reset:
    delete:
      description: Брише све запослене, смене и повезане податке из система (само
        за админе)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.MessageResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Ресетовање свих података
      tags:
      - админ
  /employees:
    get:
      description: Преузимање свих запослених
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeResponse'
              type: array
            type: array
      security:
      - BearerAuth: []
      summary: Преузимање листе запослених
      tags:
      - запослени
    post:
      consumes:
      - application/json
      description: Креирање новог запосленог у систему
      parameters:
      - description: Подаци о новом запосленом
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      summary: Креирање новог запосленог
      tags:
      - запослени
  /employees/{id}:
    delete:
      description: Брисање запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Брисање запосленог
      tags:
      - запослени
    put:
      description: Ажурирање запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци за ажурирање запосленог
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeUpdateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Ажурирање запосленог
      tags:
      - запослени
  /employees/{id}/active-emergencies:
    get:
      consumes:
      - application/json
      description: Проверава да ли запослени има активне хитне случајеве
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ActiveEmergenciesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      summary: Провера активних хитних случајева за запосленог
      tags:
      - запослени
  /employees/{id}/shifts:
    delete:
      description: Уклањање смене за запосленог по ID-ју и подацима о смени
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци о смени
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.RemoveShiftRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Уклањање смене за запосленог
      tags:
      - запослени
    get:
      description: Дохватање смена за запосленог по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Дохватање смена за запосленог
      tags:
      - запослени
    post:
      description: Додељује смену запосленом по ID-ју
      parameters:
      - description: ID запосленог
        in: path
        name: id
        required: true
        type: integer
      - description: Подаци о смени
        in: body
        name: shift
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.AssignShiftRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.AssignShiftResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Додељује смену запосленом
      tags:
      - запослени
  /employees/on-call:
    get:
      consumes:
      - application/json
      description: Враћа листу запослених који су тренутно на дужности, са опционим
        бафером у случају да се близу крај тренутне смене
      parameters:
      - description: Бафер време пре краја смене (нпр. '1h')
        in: query
        name: shift_buffer
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.OnCallEmployeesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      summary: Претрага запослених који су тренутно на дужности
      tags:
      - запослени
  /login:
    post:
      consumes:
      - application/json
      description: Пријавање запосленог са корисничким именом и лозинком
      parameters:
      - description: Корисничко име и лозинка
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.EmployeeLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.TokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      summary: Пријавање запосленог
      tags:
      - запослени
  /shifts/availability:
    get:
      description: Дохватање доступности смена за одређени дан
      parameters:
      - description: Дан за који се проверава доступност смена
        in: query
        name: date
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ShiftAvailabilityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_employee_v1.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Дохватање доступности смена
      tags:
      - запослени
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
