basePath: /api/v1
definitions:
  github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityCreateRequest:
    properties:
      description:
        type: string
      employeeId:
        type: integer
      urgencyId:
        type: integer
    required:
    - description
    - employeeId
    - urgencyId
    type: object
  github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityListResponse:
    properties:
      activities:
        items:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityResponse'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      totalPages:
        type: integer
    type: object
  github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      employeeId:
        description: ID of the employee who created the activity
        type: integer
      id:
        type: integer
      updatedAt:
        type: string
      urgencyId:
        description: ID of the urgency this activity relates to
        type: integer
    type: object
  github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityStatsResponse:
    properties:
      activitiesLast7Days:
        type: integer
      activitiesLast24h:
        type: integer
      activitiesLast30Days:
        type: integer
      recentActivities:
        items:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityResponse'
        type: array
      totalActivities:
        type: integer
    type: object
  github_com_pd120424d_mountain-service_api_contracts_activity_v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8084
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Activity tracking and audit service for the Mountain Emergency Management
    System
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Activity Service API
  version: "1.0"
paths:
  /activities:
    get:
      description: Извлачење листе активности са опционим филтрирањем и страничењем
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: pageSize
        type: integer
      - description: Activity type filter
        in: query
        name: type
        type: string
      - description: Activity level filter
        in: query
        name: level
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityListResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Листа активности
      tags:
      - activities
    post:
      consumes:
      - application/json
      description: Креирање нове активности у систему
      parameters:
      - description: Activity data
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ErrorResponse'
      summary: Креирање нове активности
      tags:
      - activities
  /activities/{id}:
    delete:
      description: Брисање одређене активности по њеном ID
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Брисање активности
      tags:
      - activities
    get:
      description: Преузимање одређене активности по њеном ID
      parameters:
      - description: Activity ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Преузимање активности по ID
      tags:
      - activities
  /activities/reset:
    delete:
      description: Брисање свих активности из система
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Ресетовање свих података о активностима
      tags:
      - activities
  /activities/stats:
    get:
      description: Преузимање свеобухватних статистика активности
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_pd120424d_mountain-service_api_contracts_activity_v1.ActivityStatsResponse'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Статистике активности
      tags:
      - activities
security:
- OAuth2Password: []
securityDefinitions:
  OAuth2Password:
    flow: password
    scopes:
      read: Grants read access
      write: Grants write access
    tokenUrl: /api/v1/oauth/token
    type: oauth2
swagger: "2.0"
