replicaCount: 1

image:
  repository: ghcr.io/pd120424d/activity-readmodel-updater
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-auth

service:
  type: ClusterIP
  port: 8090

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 512Mi

secrets:
  dbCommon: db-common
  dbService: activity-db
  cloudSQLSA: gcp-sa
  cloudSQLSAKey: key.json
  cloudSQLPrimarySecret: cloudsql-activity
  cloudSQLPrimaryKey: INSTANCE_CONNECTION_NAME
  updaterGCPKeySecret: gcp-readmodel-updater-key
  updaterGCPKeyFile: key.json
  loggingGCPKeySecret: gcp-logging-writer-key
  loggingGCPKeyFile: key.json

cloudSQL:
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4

appEnv:
  DB_HOST: 127.0.0.1
  DB_PORT: "5432"
  DB_SSLMODE: disable
  GOOGLE_CLOUD_PROJECT: reflecting-card-469410-q1
  FIREBASE_PROJECT_ID: reflecting-card-469410-q1
  PUBSUB_TOPIC: activity-events
  PUBSUB_SUBSCRIPTION: activity-events-sub
  OUTBOX_POLL_INTERVAL_SECONDS: "10"
  HEALTH_PORT: "8090"
  LOG_LEVEL: info
  GOMEMLIMIT: "400Mi"

  GCP_LOGGING_ENABLED: "true"

  SUBSCRIBER_NUM_GOROUTINES: "8"
  SUBSCRIBER_MAX_OUTSTANDING_MESSAGES: "1000"
  SUBSCRIBER_MAX_OUTSTANDING_BYTES: "104857600"
