// Code generated by MockGen. DO NOT EDIT.
// Source: azure_blob_service.go
//
// Generated by this command:
//
//	mockgen -source=azure_blob_service.go -destination=azure_blob_service_gomock.go -package=storage -imports=gomock=go.uber.org/mock/gomock
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAzureBlobService is a mock of AzureBlobService interface.
type MockAzureBlobService struct {
	ctrl     *gomock.Controller
	recorder *MockAzureBlobServiceMockRecorder
	isgomock struct{}
}

// MockAzureBlobServiceMockRecorder is the mock recorder for MockAzureBlobService.
type MockAzureBlobServiceMockRecorder struct {
	mock *MockAzureBlobService
}

// NewMockAzureBlobService creates a new mock instance.
func NewMockAzureBlobService(ctrl *gomock.Controller) *MockAzureBlobService {
	mock := &MockAzureBlobService{ctrl: ctrl}
	mock.recorder = &MockAzureBlobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureBlobService) EXPECT() *MockAzureBlobServiceMockRecorder {
	return m.recorder
}

// DeleteProfilePicture mocks base method.
func (m *MockAzureBlobService) DeleteProfilePicture(ctx context.Context, blobName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfilePicture", ctx, blobName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfilePicture indicates an expected call of DeleteProfilePicture.
func (mr *MockAzureBlobServiceMockRecorder) DeleteProfilePicture(ctx, blobName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfilePicture", reflect.TypeOf((*MockAzureBlobService)(nil).DeleteProfilePicture), ctx, blobName)
}

// UploadProfilePicture mocks base method.
func (m *MockAzureBlobService) UploadProfilePicture(ctx context.Context, file multipart.File, header *multipart.FileHeader, employeeID uint) (*UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadProfilePicture", ctx, file, header, employeeID)
	ret0, _ := ret[0].(*UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadProfilePicture indicates an expected call of UploadProfilePicture.
func (mr *MockAzureBlobServiceMockRecorder) UploadProfilePicture(ctx, file, header, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadProfilePicture", reflect.TypeOf((*MockAzureBlobService)(nil).UploadProfilePicture), ctx, file, header, employeeID)
}
