replicaCount: 1

image:
  repository: swaggerapi/swagger-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

ingress:
  enabled: true
  className: traefik
  host: mountain-service.duckdns.org
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: mountain-service-redirect-https@kubernetescrd
  tls:
    secretName: mountain-service-tls
  paths:
    - path: /docs
      pathType: Prefix

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

env:
  BASE_URL: /docs
  CONFIG_URL: /api/v1/docs/swagger-config.json
