apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: mountain-service
spec:
  selector:
    app: activity-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

