apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: mountain
spec:
  selector:
    app: employee-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  type: ClusterIP

