apiVersion: v1
kind: Service
metadata:
  name: urgency-service
  namespace: mountain
spec:
  selector:
    app: urgency-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP

