apiVersion: v1
kind: Service
metadata:
  name: version-service
  namespace: mountain-service
spec:
  selector:
    app: version-service
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP

