name: AWS Backend Deploy

on:
  workflow_run:
    workflows: ["backend-test-coverage"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild backend images'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      git_sha: ${{ steps.version.outputs.GIT_SHA }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch full git history and tags
      run: |
        git fetch --tags --unshallow || git fetch --tags

    - name: Get Git tag and SHA
      id: version
      run: |
        echo "VERSION=$(git describe --tags --abbrev=0 --match "v*" 2>/dev/null || echo dev)" >> $GITHUB_OUTPUT
        echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build-backend:
    needs: get-version
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || 
        (github.event_name == 'workflow_run' &&
         github.event.workflow_run.conclusion == 'success' &&
         github.event.workflow_run.event == 'push')
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: employee-service
            dockerfile: ./api/employee/Dockerfile
            context: ./api
            build_args: ""
          - name: urgency-service
            dockerfile: ./api/urgency/Dockerfile
            context: ./api
            build_args: ""
          - name: activity-service
            dockerfile: ./api/activity/Dockerfile
            context: ./api
            build_args: ""
          - name: version-service
            dockerfile: ./api/version-service/Dockerfile
            context: ./api
            build_args: "VERSION GIT_SHA"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Clean Docker build cache
      run: |
        echo "Cleaning Docker build cache to ensure fresh build..."
        docker builder prune -f
        docker system prune -f

    - name: Build Docker image for ${{ matrix.service.name }}
      run: |
        # Always use --no-cache to ensure fresh builds
        # This prevents issues with cached layers containing old code
        NO_CACHE_FLAG="--no-cache"

        # Add a unique build arg to bust cache and ensure fresh builds
        BUILD_TIMESTAMP=$(date +%s)

        # Add git commit SHA to ensure unique builds per commit
        GIT_COMMIT_SHA="${{ github.sha }}"

        if [ "${{ matrix.service.build_args }}" != "" ]; then
          docker build \
            -f ${{ matrix.service.dockerfile }} \
            -t ${{ matrix.service.name }}:latest \
            --build-arg VERSION=${{ needs.get-version.outputs.version }} \
            --build-arg GIT_SHA=${{ needs.get-version.outputs.git_sha }} \
            --build-arg BUILD_TIMESTAMP=$BUILD_TIMESTAMP \
            --build-arg GIT_COMMIT_SHA=$GIT_COMMIT_SHA \
            $NO_CACHE_FLAG \
            ${{ matrix.service.context }}
        else
          docker build \
            -f ${{ matrix.service.dockerfile }} \
            -t ${{ matrix.service.name }}:latest \
            --build-arg BUILD_TIMESTAMP=$BUILD_TIMESTAMP \
            --build-arg GIT_COMMIT_SHA=$GIT_COMMIT_SHA \
            $NO_CACHE_FLAG \
            ${{ matrix.service.context }}
        fi

    - name: Tag and Push ${{ matrix.service.name }} to GHCR
      run: |
        GHCR_IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ matrix.service.name }}"

        # Create unique tag using commit SHA to prevent caching issues
        COMMIT_TAG="${{ needs.get-version.outputs.git_sha }}"
        VERSION_TAG="${{ needs.get-version.outputs.version }}"

        # Tag images with multiple tags for flexibility
        docker tag ${{ matrix.service.name }}:latest ${GHCR_IMAGE_NAME}:latest
        docker tag ${{ matrix.service.name }}:latest ${GHCR_IMAGE_NAME}:${VERSION_TAG}
        docker tag ${{ matrix.service.name }}:latest ${GHCR_IMAGE_NAME}:${COMMIT_TAG}

        # Push all tags
        docker push ${GHCR_IMAGE_NAME}:latest
        docker push ${GHCR_IMAGE_NAME}:${VERSION_TAG}
        docker push ${GHCR_IMAGE_NAME}:${COMMIT_TAG}

  deploy-backend:
    needs: [get-version, build-backend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment variables
      run: |
        # Use AWS-prefixed secrets
        echo "CLOUD_INSTANCE_IP=${{ secrets.AWS_INSTANCE_IP }}" >> $GITHUB_ENV
        echo "CLOUD_INSTANCE_USER=${{ secrets.AWS_INSTANCE_USER }}" >> $GITHUB_ENV
        echo "JWT_SECRET=${{ secrets.AWS_JWT_SECRET }}" >> $GITHUB_ENV
        echo "ADMIN_PASSWORD=${{ secrets.AWS_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        echo "SERVICE_AUTH_SECRET=${{ secrets.AWS_SERVICE_AUTH_SECRET }}" >> $GITHUB_ENV
        echo "CORS_ALLOWED_ORIGINS=${{ secrets.AWS_CORS_ALLOWED_ORIGINS }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.AWS_DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.AWS_DB_PASSWORD }}" >> $GITHUB_ENV
        echo "REDIS_ADDR=${{ secrets.AWS_REDIS_ADDR }}" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=${{ secrets.AWS_REDIS_PASSWORD }}" >> $GITHUB_ENV
        echo "REDIS_DB=${{ secrets.AWS_REDIS_DB }}" >> $GITHUB_ENV
        echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
        echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV
        echo "AZURE_STORAGE_CONTAINER_NAME=${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}" >> $GITHUB_ENV
        echo "COMPOSE_ENV=production" >> $GITHUB_ENV
        echo "SWAGGER_API_URL=http://${{ secrets.AWS_INSTANCE_IP }}:8082/swagger.json" >> $GITHUB_ENV
        
        # Set image names using commit SHA to ensure unique images and prevent caching issues
        echo "EMPLOYEE_SERVICE_IMAGE=ghcr.io/${{ github.repository_owner }}/employee-service:${{ needs.get-version.outputs.git_sha }}" >> $GITHUB_ENV
        echo "URGENCY_SERVICE_IMAGE=ghcr.io/${{ github.repository_owner }}/urgency-service:${{ needs.get-version.outputs.git_sha }}" >> $GITHUB_ENV
        echo "ACTIVITY_SERVICE_IMAGE=ghcr.io/${{ github.repository_owner }}/activity-service:${{ needs.get-version.outputs.git_sha }}" >> $GITHUB_ENV
        echo "VERSION_SERVICE_IMAGE=ghcr.io/${{ github.repository_owner }}/version-service:${{ needs.get-version.outputs.git_sha }}" >> $GITHUB_ENV
        echo "FRONTEND_IMAGE=ghcr.io/${{ github.repository_owner }}/frontend:latest" >> $GITHUB_ENV

    - name: Create backend deployment environment file
      run: |
        cat > .env.backend << EOF
        # Backend Deployment Configuration
        CLOUD_INSTANCE_IP=${{ env.CLOUD_INSTANCE_IP }}
        CLOUD_INSTANCE_USER=${{ env.CLOUD_INSTANCE_USER }}
        INSTANCE_IP=${{ env.CLOUD_INSTANCE_IP }}
        INSTANCE_USER=${{ env.CLOUD_INSTANCE_USER }}
        SSH_KEY_PATH=~/.ssh/deploy_key

        # Docker Images
        EMPLOYEE_SERVICE_IMAGE=${{ env.EMPLOYEE_SERVICE_IMAGE }}
        URGENCY_SERVICE_IMAGE=${{ env.URGENCY_SERVICE_IMAGE }}
        ACTIVITY_SERVICE_IMAGE=${{ env.ACTIVITY_SERVICE_IMAGE }}
        VERSION_SERVICE_IMAGE=${{ env.VERSION_SERVICE_IMAGE }}
        FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}

        # GitHub Container Registry Authentication
        GHCR_PAT=${{ secrets.GHCR_PAT }}
        GITHUB_ACTOR=${{ github.actor }}

        # Application Security
        JWT_SECRET=${{ env.JWT_SECRET }}
        ADMIN_PASSWORD=${{ env.ADMIN_PASSWORD }}
        SERVICE_AUTH_SECRET=${{ env.SERVICE_AUTH_SECRET }}
        CORS_ALLOWED_ORIGINS=${{ env.CORS_ALLOWED_ORIGINS }}

        # Database Configuration
        DB_USER=${{ env.DB_USER }}
        DB_PASSWORD=${{ env.DB_PASSWORD }}

        # Redis Configuration
        REDIS_ADDR=${{ env.REDIS_ADDR }}
        REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
        REDIS_DB=${{ env.REDIS_DB }}

        # Azure Storage Configuration
        AZURE_STORAGE_ACCOUNT_NAME=${{ env.AZURE_STORAGE_ACCOUNT_NAME }}
        AZURE_STORAGE_ACCOUNT_KEY=${{ env.AZURE_STORAGE_ACCOUNT_KEY }}
        AZURE_STORAGE_CONTAINER_NAME=${{ env.AZURE_STORAGE_CONTAINER_NAME }}

        # Service URLs
        EMPLOYEE_SERVICE_URL=http://employee-service:8082
        ACTIVITY_SERVICE_URL=http://activity-service:8084

        # Frontend Configuration
        FRONTEND_HTTP_PORT=80
        FRONTEND_HTTPS_PORT=443
        NODE_ENV=production
        APP_ENV=production

        # Database Ports
        EMPLOYEE_DB_PORT=5432
        URGENCY_DB_PORT=5433
        ACTIVITY_DB_PORT=5434

        # Additional Configuration
        COMPOSE_ENV=${{ env.COMPOSE_ENV }}
        SWAGGER_API_URL=${{ env.SWAGGER_API_URL }}
        EOF

        echo "Backend deployment .env file created"

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H ${{ env.CLOUD_INSTANCE_IP }} >> ~/.ssh/known_hosts

    - name: Deploy backend to AWS
      run: |
        export SSH_KEY_CONTENT="${{ secrets.AWS_SSH_PRIVATE_KEY }}"
        export SSH_KEY_PATH="~/.ssh/deploy_key"
        export GHCR_PAT="${{ secrets.GHCR_PAT }}"
        export GITHUB_ACTOR="${{ github.actor }}"
        export FRONTEND_IMAGE="ghcr.io/${{ github.repository_owner }}/frontend:latest"

        # Make deployment script executable
        chmod +x ./deploy-backend.sh

        # Run backend deployment
        ./deploy-backend.sh .env.backend

    - name: Verify backend deployment
      run: |
        echo "Waiting for backend services to start..."
        sleep 30

        # Colors for output
        RED='\033[0;31m'
        GREEN='\033[0;32m'
        YELLOW='\033[1;33m'
        NC='\033[0m' # No Color

        echo "Testing backend services through nginx proxy..."

        # Test employee service health
        echo -n "Testing employee service health... "
        if curl -f -s http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/health > /dev/null 2>&1; then
          echo -e "${GREEN} PASSED${NC}"
        else
          echo -e "${RED} FAILED${NC}"
          echo -e "${YELLOW} WARNING: Employee service health check failed - this may cause 502 errors${NC}"
        fi

        # Test version service
        echo -n "Testing version service... "
        if curl -f -s http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/version > /dev/null 2>&1; then
          echo -e "${GREEN} PASSED${NC}"
        else
          echo -e "${RED} FAILED${NC}"
          echo -e "${YELLOW} WARNING: Version service check failed${NC}"
        fi

        # Verify all backend containers are running
        echo "Verifying all backend containers are running..."
        ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ env.CLOUD_INSTANCE_USER }}@${{ env.CLOUD_INSTANCE_IP }} "docker ps --format 'table {{.Names}}\t{{.Status}}' | grep -E '(employee|urgency|activity|version)'"

        echo -e "${GREEN} Backend deployment verification completed!${NC}"

    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/deploy_key
        rm -f .env.backend

    - name: Backend Deployment Summary
      run: |
        echo "## Backend Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Target Platform**: AWS" >> $GITHUB_STEP_SUMMARY
        echo "- **Instance**: ${{ env.CLOUD_INSTANCE_USER }}@${{ env.CLOUD_INSTANCE_IP }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Employee API**: http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/employees" >> $GITHUB_STEP_SUMMARY
        echo "- **Urgency API**: http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/urgencies" >> $GITHUB_STEP_SUMMARY
        echo "- **Activity API**: http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/activities" >> $GITHUB_STEP_SUMMARY
        echo "- **Version API**: http://${{ env.CLOUD_INSTANCE_IP }}/api/v1/version" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Backend Images Deployed**:" >> $GITHUB_STEP_SUMMARY
        echo "- Employee Service: ${{ env.EMPLOYEE_SERVICE_IMAGE }}" >> $GITHUB_STEP_SUMMARY
        echo "- Urgency Service: ${{ env.URGENCY_SERVICE_IMAGE }}" >> $GITHUB_STEP_SUMMARY
        echo "- Activity Service: ${{ env.ACTIVITY_SERVICE_IMAGE }}" >> $GITHUB_STEP_SUMMARY
        echo "- Version Service: ${{ env.VERSION_SERVICE_IMAGE }}" >> $GITHUB_STEP_SUMMARY
