name: backend-test-coverage

on:
  pull_request:
    paths:
      - 'api/**'
      - 'backend-test-cover.sh'
      - '.github/workflows/backend-test-coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: api/go.sum

      - name: Run test coverage check
        env:
          VERBOSE: '1'
          TIMEOUT_SECONDS: '900'
        run: ./backend-test-cover.sh all --threshold=75
