name: backend-test-coverage

on:
  pull_request:
    paths:
      - 'api/**'
      - 'backend-test-cover.sh'
      - '.github/workflows/backend-test-coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [activity, employee, urgency, activity-readmodel-updater]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
          cache-dependency-path: api/go.sum

      - name: Run test coverage check for ${{ matrix.service }}
        env:
          VERBOSE: '1'
          TIMEOUT_SECONDS: '900'
          THRESHOLD: '75.0'
        run: ./backend-test-cover.sh ${{ matrix.service }}
