name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build -t frontend:latest -f ./ui/Dockerfile ./ui
        docker build -t employee-service:latest -f ./api/employee/Dockerfile ./api

    - name: Save Docker images as tarballs
      run: |
        docker save frontend:latest > frontend.tar
        docker save employee-service:latest > employee.tar

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
        chmod 600 ~/.ssh/github_actions
        ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -i ~/.ssh/github_actions -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "echo connected successfully"

    - name: Copy Docker images to Azure VM
      run: |
        scp -i ~/.ssh/github_actions frontend.tar employee.tar ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:~

    - name: Load and run Docker containers on Azure VM
      run: |
        ssh -i ~/.ssh/github_actions ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} '
          set -e
          docker load < ~/frontend.tar
          docker load < ~/employee.tar
          rm ~/frontend.tar ~/employee.tar

          cd mountain-service

          # Injecting the secret as environment variable
          echo "SWAGGER_API_URL=${{ secrets.SWAGGER_API_URL }}" > .env
          echo "CORS_ALLOWED_ORIGINS=http://${{ secrets.AZURE_VM_HOST }}:9082" >> .env

          git pull origin main

          docker compose -f docker-compose.prod.yml down
          docker compose -f docker-compose.prod.yml up -d
        '
