name: frontend-test-coverage

on:
  push:
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'
  pull_request:
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.19
        uses: actions/setup-node@v3
        with:
          node-version: 18.19

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests with coverage
        run: npm run test

