name: frontend-test-coverage

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'
  pull_request:
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js (20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run frontend coverage script
        run: ../frontend-test-cover.sh
