name: frontend-test-coverage

on:
  push:
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'
  pull_request:
    paths:
      - 'ui/**'
      - 'frontend-test-cover.sh'
      - '.github/workflows/frontend-test-coverage.yml'

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.19
        uses: actions/setup-node@v3
        with:
          node-version: 18.19

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run frontend coverage script
        run: ./frontend-test-cover.sh
